import type { BundleItem } from "./types";

export function wikiImage(fileName: string) {
  return `https://stardewvalleywiki.com/mediawiki/index.php?title=Special:Redirect/file/${encodeURIComponent(
    fileName,
  )}`;
}

export const itemImageFiles: Record<string, string> = {
  "spring-foraging-wild-horseradish": "Wild_Horseradish.png",
  "spring-foraging-daffodil": "Daffodil.png",
  "spring-foraging-leek": "Leek.png",
  "spring-foraging-dandelion": "Dandelion.png",
  "spring-crops-parsnip": "Parsnip.png",
  "spring-crops-green-bean": "Green_Bean.png",
  "spring-crops-cauliflower": "Cauliflower.png",
  "spring-crops-potato": "Potato.png",
  "quality-parsnip": "Parsnip.png",
  "summer-foraging-grape": "Grape.png",
  "summer-foraging-spice-berry": "Spice_Berry.png",
  "summer-foraging-sweet-pea": "Sweet_Pea.png",
  "summer-crops-tomato": "Tomato.png",
  "summer-crops-hot-pepper": "Hot_Pepper.png",
  "summer-crops-blueberry": "Blueberry.png",
  "summer-crops-melon": "Melon.png",
  "quality-melon": "Melon.png",
  "fall-foraging-common-mushroom": "Common_Mushroom.png",
  "fall-foraging-wild-plum": "Wild_Plum.png",
  "fall-foraging-hazelnut": "Hazelnut.png",
  "fall-foraging-blackberry": "Blackberry.png",
  "fall-crops-corn": "Corn.png",
  "fall-crops-eggplant": "Eggplant.png",
  "fall-crops-pumpkin": "Pumpkin.png",
  "fall-crops-yam": "Yam.png",
  "quality-pumpkin": "Pumpkin.png",
  "quality-corn": "Corn.png",
  "animal-large-milk": "Large_Milk.png",
  "animal-large-egg": "Large_Egg.png",
  "animal-large-brown-egg": "Large_Brown_Egg.png",
  "animal-large-goat-milk": "Large_Goat_Milk.png",
  "animal-wool": "Wool.png",
  "artisan-honey": "Honey.png",
  "artisan-jelly": "Jelly.png",
  "artisan-cheese": "Cheese.png",
  "artisan-cloth": "Cloth.png",
  "artisan-apple": "Apple.png",
  "artisan-pomegranate": "Pomegranate.png",
  "river-sunfish": "Sunfish.png",
  "river-catfish": "Catfish.png",
  "river-shad": "Shad.png",
  "river-tiger-trout": "Tiger_Trout.png",
  "lake-largemouth-bass": "Largemouth_Bass.png",
  "lake-carp": "Carp.png",
  "lake-bullhead": "Bullhead.png",
  "lake-sturgeon": "Sturgeon.png",
  "ocean-sardine": "Sardine.png",
  "ocean-tuna": "Tuna.png",
  "ocean-red-snapper": "Red_Snapper.png",
  "ocean-tilapia": "Tilapia.png",
  "night-walleye": "Walleye.png",
  "night-bream": "Bream.png",
  "night-eel": "Eel.png",
  "crab-lobster": "Lobster.png",
  "crab-crab": "Crab.png",
  "crab-clam": "Clam.png",
  "crab-crayfish": "Crayfish.png",
  "crab-cockle": "Cockle.png",
  "crab-mussel": "Mussel.png",
  "crab-shrimp": "Shrimp.png",
  "crab-snail": "Snail.png",
  "crab-periwinkle": "Periwinkle.png",
  "crab-oyster": "Oyster.png",
  "specialty-pufferfish": "Pufferfish.png",
  "specialty-ghostfish": "Ghostfish.png",
  "specialty-sandfish": "Sandfish.png",
  "specialty-woodskip": "Woodskip.png",
  "blacksmith-copper-bar": "Copper_Bar.png",
  "blacksmith-iron-bar": "Iron_Bar.png",
  "blacksmith-gold-bar": "Gold_Bar.png",
  "geologist-quartz": "Quartz.png",
  "geologist-earth-crystal": "Earth_Crystal.png",
  "geologist-frozen-tear": "Frozen_Tear.png",
  "geologist-fire-quartz": "Fire_Quartz.png",
  "adventurer-slime": "Slime.png",
  "adventurer-bat-wing": "Bat_Wing.png",
  "chef-maple-syrup": "Maple_Syrup.png",
  "chef-fiddlehead-fern": "Fiddlehead_Fern.png",
  "chef-truffle": "Truffle.png",
  "chef-poppy": "Poppy.png",
  "chef-maki-roll": "Maki_Roll.png",
  "chef-fried-egg": "Fried_Egg.png",
  "dye-red-mushroom": "Red_Mushroom.png",
  "dye-sea-urchin": "Sea_Urchin.png",
  "dye-sunflower": "Sunflower.png",
  "dye-duck-feather": "Duck_Feather.png",
  "dye-aquamarine": "Aquamarine.png",
  "dye-red-cabbage": "Red_Cabbage.png",
  "field-fodder-wheat": "Wheat.png",
  "field-fodder-hay": "Hay.png",
  "field-fodder-apple": "Apple.png",
  "enchanter-oak-resin": "Oak_Resin.png",
  "enchanter-wine": "Wine.png",
  "enchanter-rabbit-foot": "Rabbit's_Foot.png",
  "enchanter-pomegranate": "Pomegranate.png",
  "winter-foraging-winter-root": "Winter_Root.png",
  "winter-foraging-crystal-fruit": "Crystal_Fruit.png",
  "winter-foraging-snow-yam": "Snow_Yam.png",
  "winter-foraging-crocus": "Crocus.png",
  "exotic-coconut": "Coconut.png",
  "exotic-cactus-fruit": "Cactus_Fruit.png",
  "exotic-cave-carrot": "Cave_Carrot.png",
  "exotic-red-mushroom": "Red_Mushroom.png",
  "exotic-purple-mushroom": "Purple_Mushroom.png",
  "exotic-maple-syrup": "Maple_Syrup.png",
  "exotic-oak-resin": "Oak_Resin.png",
  "exotic-pine-tar": "Pine_Tar.png",
  "exotic-morel": "Morel.png",
  "construction-wood": "Wood.png",
  "construction-wood-2": "Wood.png",
  "construction-stone": "Stone.png",
  "construction-hardwood": "Hardwood.png",
  "vault-2500": "Gold.png",
  "vault-5000": "Gold.png",
  "vault-10000": "Gold.png",
  "vault-25000": "Gold.png",
};

export function getItemImageUrl(item: BundleItem) {
  const fileName = itemImageFiles[item.id] ?? `${item.name.replaceAll(" ", "_")}.png`;
  return `/stardew/items/${fileName}`;
}
